# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6369a70292e7b7084220c535eb76cda86a7dc4b09a2263d0250094c3a973e352d68467bcd0632f95be47e67684f65de03e86780032339e494ad182a40c71eef6

test:
  secret_key_base: 97f1c6f8e56c92daedcb8ca82ae68f608dbdd8cb163fb000382614952cb321b2b6e7a69e7f65f0a3bad4db49aed3704b311cbf6e57bf8dd6d070af7e26760c16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
